#!/bin/bash
pdflatex -interaction=nonstopmode sudipta_banik_software_engineer_resume.tex
pdflatex -interaction=nonstopmode sudipta_banik_software_engineer_resume.tex

cp sudipta_banik_software_engineer_resume.pdf ../sudipta_banik_software_engineer_resume.pdf
cp sudipta_banik_software_engineer_resume.pdf ~/Downloads/Resumes/sudipta_banik_software_engineer_resume.pdf